# The URL the site will be built for
base_url = "https://novemberkilo.com"

title = "The iNK blot"
# a description; you can use markdown here if you like
default_language = "en"

theme = "hermit_zola"
# theme = "hyde"

# Whether to generate a RSS feed automatically
generate_feed = true
feed_filename = "rss.xml"

taxonomies = [
    {name = "tags", feed = true}
]

# Whether to compile the Sass files found in the `sass` directory
compile_sass = true

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[extra]
home_subtitle = ""

footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a>'

hermit_menu = [
    { link = "/posts", name = "Posts" },
    { link = "/about", name = "About" }
]

hermit_social = [
    # { name = "twitter", link = "https://twitter.com/novemberkilo" },
    { name = "linkedin", link = "https://www.linkedin.com/in/novemberkilo" },
    { name = "github", link = "https://github.com/novemberkilo" },
    # { name = "email", link = "mailto: navin@novemberkilo.com" }
]

[extra.author]
name = "novemberkilo"
email = "navin@novemberkilo.com"

[extra.google_analytics]
enable = false
id = "UA-4XXXXXXX-X"
