# The URL the site will be built for
base_url = "https://novemberkilo.com"

title = "The iNK blot"
# a description; you can use markdown here if you like
default_language = "en"

theme = "hermit_zola"
# theme = "hyde"

# Highlight all code blocks found
highlight_code = true

# Which theme to use for the code highlighting.
# See below for list of accepted values
highlight_theme = "gruvbox-dark"

# Whether to generate a RSS feed automatically
generate_rss = true

# The number of articles to include in the RSS feed. Will include all items if
# not set (the default).
# rss_limit = 20

# The taxonomies to be rendered for that site and their configuration
# Example:
#     taxonomies = [
#       {name = "tags", rss = true}, # each tag will have its own RSS feed
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no RSS or pagination
#     ]
#
taxonomies = [
    {name = "tags", rss = true}
]

# The additional languages for that site
# Example:
#     languages = [
#       {code = "fr", rss = true}, # there will be a RSS feed for French content
#       {code = "it"}, # there won't be a RSS feed for Italian content
#     ]
#
languages = []

# Whether to compile the Sass files found in the `sass` directory
compile_sass = true

[extra]
home_subtitle = ""

footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a>'

hermit_menu = [
    { link = "/posts", name = "Posts" },
    { link = "/about", name = "About" }
]

hermit_social = [
    # { name = "twitter", link = "https://twitter.com/novemberkilo" },
    { name = "linkedin", link = "https://www.linkedin.com/in/novemberkilo" },
    { name = "github", link = "https://github.com/novemberkilo" },
    # { name = "email", link = "mailto: navin@novemberkilo.com" }
]

[extra.author]
name = "novemberkilo"
email = "navin@novemberkilo.com"

[extra.google_analytics]
enable = false
id = "UA-4XXXXXXX-X"
